######################################################################
# Automatically generated by qmake (3.0) ?? 8? 4 08:47:01 2016
######################################################################

TEMPLATE = app
TARGET = Amerda
INCLUDEPATH += .

# Input
HEADERS += amerdawidget.h qcustomplot.h \
    helper.h
FORMS += amerdawidget.ui
SOURCES += amerdawidget.cpp main.cpp qcustomplot.cpp \
    helper.cpp


QT +=gui core  widgets  printsupport
